EXCEL_TO_DB_MAP = {
    "SKU Parent Code": "sku_parent_code",
    "SKU Code": "sku_code",
    "SKU Description": "sku_description",
    "Warehouse": "warehouse",
    "Hyper A": "hyper_a",
    "Hyper B": "hyper_b",
    "Super A": "super_a",
    "Super B": "super_b",
    "Minimart A": "minimart_a",
    "Minimart B": "minimart_b",
    "Grocery A": "grocery_a",
    "Grocery B": "grocery_b",
    "Grocery C": "grocery_c",
    "ECom A": "ecom_a",
    "ECom B": "ecom_b",
    "Petrol Pumps A": "petrol_pumps_a",
    "Petrol Pumps B": "petrol_pumps_b",
    "Petrol Pumps C": "petrol_pumps_c",
    "Pharmacy A": "pharmacy_a",
    "Pharmacy B": "pharmacy_b",
    "Pharmacy C": "pharmacy_c",
    "Wholesale": "wholesale",
    "Horeca": "horeca",
}
