EXCEL_TO_DB_MAP = {
    "SKU Parent Code": "sku_parent_code",
    "SKU Code": "sku_code",
    "Case Barcode": "case_barcode",
    "Outer Barcode": "outer_barcode",
    "Unit Barcode": "unit_barcode",
    "SKU Description": "sku_description",
    "Unit Images": "unit_images",
    "Outer Images": "outer_images",
    "Cases Images": "cases_images",
    "Master Distributor": "master_distributor",
    "Distributor": "distributor",
    "Line of Business": "line_of_business",
    "Supplier": "supplier",
    "Agency": "agency",
    "Category": "category",
    "Segment": "segment",
    "Brand": "brand",
    "Sub Brand": "sub_brand",
    "SKU Type": "sku_type",
    "Promotion": "promotion",
    "SKU Status": "sku_status",
    "Shelf Life (Days)": "shelf_life_days",
    "Temperature": "temperature",
    "Case Length (Cm)": "case_length_cm",
    "Case Width (Cm)": "case_width_cm",
    "Case Height (Cm)": "case_height_cm",
    "Case (CBM)": "case_cbm",
    "Outer Length (Cm)": "outer_length_cm",
    "Outer Width (Cm)": "outer_width_cm",
    "Outer Height (Cm)": "outer_height_cm",
    "Outer (CBM)": "outer_cbm",
    "Unit Length (Cm)": "unit_length_cm",
    "Unit Width (Cm)": "unit_width_cm",
    "Unit Height (Cm)": "unit_height_cm",
    "Unit (CBM)": "unit_cbm",
    "Unit Weight (Gm)": "unit_weight_gm",
    "Outer/Case": "outer_per_case",
    "Units/Outer": "units_per_outer",
    "Case Weight (Kg)": "case_weight_kg",
    "Case Cost": "case_cost",
    "Case Price": "case_price",
    "Outer Price": "outer_price",
    "Unit Price": "unit_price",
    "Unit RSP": "unit_rsp",
}