EXCEL_TO_DB_MAP = {
    "Region": "region",
    "Country": "country",
    "Master Distributor": "master_distributor",
    "Retailer Code": "retailer_code",
    "Retailer": "retailer_name",
    "Store Code": "store_code",
    "Store Name": "store_name",
    "Distributor": "distributor",
    "Line of Business": "line_of_business",
    "City": "city",
    "Area": "area",
    "Retailer Group": "retailer_group",
    "Retailer Sub Group": "retailer_sub_group",
    "Channel": "channel",
    "Sub Channel": "sub_channel",
    "Store Status": "store_status",
    "Central Buying": "central_buying",
    "Central Store Code": "central_store_code",
    "Salesmen": "salesmen",
    "GPS Coordinate": "gps_coordinate",
}
